spring:
  application:
    name: webprotege-robot-service
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      host: localhost
      port: 27017
      database: webprotege
      auto-index-creation: true
webprotege:
  directories:
    data: ${WEBPROTEGE_DATA_DIR}
  rabbitmq:
    requestqueue: webprotege-robot-queue
    responsequeue: webprotege-robot-response-queue
    timeout: 60000
  minio:
    access-key: webprotege
    end-point: http://localhost:9000
    secret-key: webprotege
    robot-output-documents-bucket-name: webprotege-robot-output-documents
  robot:
    executor:
      core-pool-size: 2
      max-pool-size: 4
      queue-capacity: 100
      thread-name-prefix: robot-pipeline-
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 60
